#!/bin/bash
# ─────────────────────────────────────────────
# 🥭 MangoLove — Work Logger
# Automatically logs session activity to a private GitHub repo
# ─────────────────────────────────────────────

MANGOLOVE_DIR="${MANGOLOVE_DIR:-$HOME/.mangolove}"
LOG_DIR="$MANGOLOVE_DIR/logs"

# Load user config
[ -f "$MANGOLOVE_DIR/config.sh" ] && source "$MANGOLOVE_DIR/config.sh"

# Determine repo name
get_repo_info() {
    if [ -n "$MANGOLOVE_LOG_REPO" ] && [ "$MANGOLOVE_LOG_REPO" != "disabled" ]; then
        REPO_FULL="$MANGOLOVE_LOG_REPO"
    else
        local gh_user=$(gh api user --jq '.login' 2>/dev/null)
        if [ -z "$gh_user" ]; then
            echo "⚠️  GitHub CLI not authenticated. Run: gh auth login"
            return 1
        fi
        REPO_FULL="${gh_user}/mangolove-work-logs"
    fi

    REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
    REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)
    REPO_URL="https://github.com/${REPO_FULL}.git"
    LOCAL_REPO="$LOG_DIR/repo"
}

init_repo() {
    get_repo_info || return 1

    if [ "$MANGOLOVE_LOG_REPO" = "disabled" ]; then
        echo "📝 Work logging is disabled."
        return 0
    fi

    if [ ! -d "$LOCAL_REPO/.git" ]; then
        if ! gh repo view "$REPO_FULL" > /dev/null 2>&1; then
            echo "📦 Creating private repository: ${REPO_FULL}..."
            gh repo create "$REPO_NAME" --private --description "MangoLove AI Agent — Work Logs 🥭"

            mkdir -p "$LOCAL_REPO"
            cd "$LOCAL_REPO"
            git init
            git remote add origin "$REPO_URL"

            cat > README.md << 'EOF'
# 🥭 MangoLove Work Logs

MangoLove AI Agent의 작업 내역을 자동으로 기록하는 저장소입니다.

## Structure
```
logs/
└── YYYY/
    └── MM/
        └── YYYY-MM-DD.md      # Daily work log
```

---
*Automatically generated by [MangoLove](https://github.com/SongJunSub/mangolove)* 🥭♥
EOF
            git add .
            git commit -m "chore: initialize mangolove work logs 🥭"
            git branch -M main
            git push -u origin main
            cd - > /dev/null
            echo "✅ Work log repository created: https://github.com/${REPO_FULL}"
        else
            echo "📥 Cloning existing work log repository..."
            git clone "$REPO_URL" "$LOCAL_REPO" 2>/dev/null
        fi
    else
        if [ -d "$LOCAL_REPO/.git" ]; then
            cd "$LOCAL_REPO" && git pull --rebase origin main 2>/dev/null || true
            cd - > /dev/null
        fi
    fi
}

log_session_start() {
    get_repo_info || return 1
    [ "$MANGOLOVE_LOG_REPO" = "disabled" ] && return 0
    [ ! -d "$LOCAL_REPO/.git" ] && init_repo

    local today=$(date '+%Y-%m-%d')
    local now=$(date '+%H:%M:%S')
    local year=$(date '+%Y')
    local month=$(date '+%m')
    local dir="$LOCAL_REPO/logs/${year}/${month}"
    local file="$dir/${today}.md"
    local project_dir=$(pwd)
    local project_name=$(basename "$project_dir")

    mkdir -p "$dir"

    # Save session metadata for auto-summary
    echo "$(date '+%Y-%m-%d %H:%M:%S')" > "$LOG_DIR/.session_start"
    echo "$project_dir" > "$LOG_DIR/.session_dir"

    if [ ! -f "$file" ]; then
        cat > "$file" << EOF
# 📅 ${today} — MangoLove Work Log

---

EOF
    fi

    cat >> "$file" << EOF
## 🕐 Session: ${now}
- **Directory**: \`${project_dir}\`
- **Project**: ${project_name}
- **Branch**: $(git branch --show-current 2>/dev/null || echo "N/A")

### Tasks

EOF

    cd "$LOCAL_REPO"
    git add . 2>/dev/null
    git commit -m "docs: session start — ${project_name} (${now})" 2>/dev/null
    git push origin main 2>/dev/null
    cd - > /dev/null
}

log_session_end() {
    get_repo_info || return 1
    [ "$MANGOLOVE_LOG_REPO" = "disabled" ] && return 0

    local today=$(date '+%Y-%m-%d')
    local now=$(date '+%H:%M:%S')
    local year=$(date '+%Y')
    local month=$(date '+%m')
    local file="$LOCAL_REPO/logs/${year}/${month}/${today}.md"

    if [ -f "$file" ]; then
        # Auto-summarize git commits made during this session
        local session_summary=""
        session_summary=$(collect_session_commits)

        if [ -n "$session_summary" ]; then
            echo "" >> "$file"
            echo "#### 📝 Changes Made" >> "$file"
            echo "$session_summary" >> "$file"
        fi

        echo "" >> "$file"
        echo "#### ⏹ Session ended: ${now}" >> "$file"
        echo "" >> "$file"
        echo "---" >> "$file"

        cd "$LOCAL_REPO"
        git add . 2>/dev/null
        git commit -m "docs: session end (${now})" 2>/dev/null
        git push origin main 2>/dev/null
        cd - > /dev/null
    fi
}

# Collect git commits made during the current session (runs in subshell)
collect_session_commits() {
    local session_start_file="$LOG_DIR/.session_start"
    [ ! -f "$session_start_file" ] && return 0

    local start_time=$(cat "$session_start_file" 2>/dev/null)
    local work_dir=$(cat "$LOG_DIR/.session_dir" 2>/dev/null)

    [ -z "$start_time" ] || [ -z "$work_dir" ] && return 0
    [ ! -d "$work_dir/.git" ] && return 0

    # Run in subshell to avoid directory change side effects
    (
        cd "$work_dir" 2>/dev/null || exit 0

        # Get commits made after session start
        local commits=""
        commits=$(git log --after="$start_time" --format="- **%h** %s" --no-merges 2>/dev/null)

        if [ -n "$commits" ]; then
            echo "$commits"
        fi

        # Get changed file stats
        local stats=""
        stats=$(git log --after="$start_time" --format="" --stat --no-merges 2>/dev/null | tail -1)

        if [ -n "$stats" ]; then
            echo ""
            echo "> ${stats}"
        fi
    )
}

# Search work logs
search_logs() {
    local keyword="$1"
    if [ -z "$keyword" ]; then
        echo "Usage: mangolove log search <keyword>"
        return 1
    fi

    get_repo_info || return 1
    [ ! -d "$LOCAL_REPO/logs" ] && echo "No logs found." && return 1

    echo ""
    echo -e "\033[38;5;208m\033[1m🥭 MangoLove — Log Search\033[0m"
    echo -e "\033[2m──────────────────────────────────────\033[0m"
    echo -e "  \033[2mKeyword:\033[0m ${keyword}"
    echo ""

    grep -rn -F --color=always "$keyword" "$LOCAL_REPO/logs/" 2>/dev/null | \
        sed "s|$LOCAL_REPO/logs/||g" | \
        head -50

    echo ""
}

# Show recent log summary
show_recent() {
    get_repo_info || return 1
    [ ! -d "$LOCAL_REPO/logs" ] && echo "No logs found." && return 1

    echo ""
    echo -e "\033[38;5;208m\033[1m🥭 MangoLove — Recent Sessions\033[0m"
    echo -e "\033[2m──────────────────────────────────────\033[0m"

    local count=0
    find "$LOCAL_REPO/logs" -name "*.md" -type f 2>/dev/null | sort -r | head -7 | while IFS= read -r logfile; do
        local date_str=$(basename "$logfile" .md)
        local sessions=$(grep -c "^## 🕐 Session:" "$logfile" 2>/dev/null || echo "0")
        local commits=$(grep -c "^\- \*\*[a-f0-9]" "$logfile" 2>/dev/null || echo "0")
        echo -e "  \033[38;5;113m▸\033[0m \033[1m${date_str}\033[0m — ${sessions} session(s), ${commits} commit(s)"
        count=$((count + 1))
    done

    # Check if any output was produced (count is in subshell, re-check)
    local total=$(find "$LOCAL_REPO/logs" -name "*.md" -type f 2>/dev/null | head -1)
    [ -z "$total" ] && echo -e "  \033[2mNo logs found.\033[0m"
    echo ""
}

# Entrypoint
case "${1:-}" in
    start)  log_session_start ;;
    end)    log_session_end ;;
    init)   init_repo ;;
    search) search_logs "$2" ;;
    recent) show_recent ;;
    *)      echo "Usage: work-logger.sh [start|end|init|search|recent]" ;;
esac
