#!/bin/bash
# ─────────────────────────────────────────────
# 🥭 MangoLove — Work Logger
# Automatically logs session activity to a private GitHub repo
# ─────────────────────────────────────────────

MANGOLOVE_DIR="${MANGOLOVE_DIR:-$HOME/.mangolove}"
LOG_DIR="$MANGOLOVE_DIR/logs"

# Load user config
[ -f "$MANGOLOVE_DIR/config.sh" ] && source "$MANGOLOVE_DIR/config.sh"

# Determine repo name
get_repo_info() {
    if [ -n "$MANGOLOVE_LOG_REPO" ] && [ "$MANGOLOVE_LOG_REPO" != "disabled" ]; then
        REPO_FULL="$MANGOLOVE_LOG_REPO"
    else
        local gh_user=$(gh api user --jq '.login' 2>/dev/null)
        if [ -z "$gh_user" ]; then
            echo "⚠️  GitHub CLI not authenticated. Run: gh auth login"
            return 1
        fi
        REPO_FULL="${gh_user}/mangolove-work-logs"
    fi

    REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
    REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)
    REPO_URL="https://github.com/${REPO_FULL}.git"
    LOCAL_REPO="$LOG_DIR/repo"
}

init_repo() {
    get_repo_info || return 1

    if [ "$MANGOLOVE_LOG_REPO" = "disabled" ]; then
        echo "📝 Work logging is disabled."
        return 0
    fi

    if [ ! -d "$LOCAL_REPO/.git" ]; then
        if ! gh repo view "$REPO_FULL" > /dev/null 2>&1; then
            echo "📦 Creating private repository: ${REPO_FULL}..."
            gh repo create "$REPO_NAME" --private --description "MangoLove AI Agent — Work Logs 🥭"

            mkdir -p "$LOCAL_REPO"
            cd "$LOCAL_REPO"
            git init
            git remote add origin "$REPO_URL"

            cat > README.md << 'EOF'
# 🥭 MangoLove Work Logs

MangoLove AI Agent의 작업 내역을 자동으로 기록하는 저장소입니다.

## Structure
```
logs/
└── YYYY/
    └── MM/
        └── YYYY-MM-DD.md      # Daily work log
```

---
*Automatically generated by [MangoLove](https://github.com/SongJunSub/mangolove)* 🥭♥
EOF
            git add .
            git commit -m "chore: initialize mangolove work logs 🥭"
            git branch -M main
            git push -u origin main
            cd - > /dev/null
            echo "✅ Work log repository created: https://github.com/${REPO_FULL}"
        else
            echo "📥 Cloning existing work log repository..."
            git clone "$REPO_URL" "$LOCAL_REPO" 2>/dev/null
        fi
    else
        cd "$LOCAL_REPO" && git pull --rebase origin main 2>/dev/null
        cd - > /dev/null
    fi
}

log_session_start() {
    get_repo_info || return 1
    [ "$MANGOLOVE_LOG_REPO" = "disabled" ] && return 0
    [ ! -d "$LOCAL_REPO/.git" ] && init_repo

    local today=$(date '+%Y-%m-%d')
    local now=$(date '+%H:%M:%S')
    local year=$(date '+%Y')
    local month=$(date '+%m')
    local dir="$LOCAL_REPO/logs/${year}/${month}"
    local file="$dir/${today}.md"
    local project_dir=$(pwd)
    local project_name=$(basename "$project_dir")

    mkdir -p "$dir"

    if [ ! -f "$file" ]; then
        cat > "$file" << EOF
# 📅 ${today} — MangoLove Work Log

---

EOF
    fi

    cat >> "$file" << EOF
## 🕐 Session: ${now}
- **Directory**: \`${project_dir}\`
- **Project**: ${project_name}
- **Branch**: $(git branch --show-current 2>/dev/null || echo "N/A")

### Tasks

EOF

    cd "$LOCAL_REPO"
    git add . 2>/dev/null
    git commit -m "docs: session start — ${project_name} (${now})" 2>/dev/null
    git push origin main 2>/dev/null
    cd - > /dev/null
}

log_session_end() {
    get_repo_info || return 1
    [ "$MANGOLOVE_LOG_REPO" = "disabled" ] && return 0

    local today=$(date '+%Y-%m-%d')
    local now=$(date '+%H:%M:%S')
    local year=$(date '+%Y')
    local month=$(date '+%m')
    local file="$LOCAL_REPO/logs/${year}/${month}/${today}.md"

    if [ -f "$file" ]; then
        echo "" >> "$file"
        echo "#### ⏹ Session ended: ${now}" >> "$file"
        echo "" >> "$file"
        echo "---" >> "$file"

        cd "$LOCAL_REPO"
        git add . 2>/dev/null
        git commit -m "docs: session end (${now})" 2>/dev/null
        git push origin main 2>/dev/null
        cd - > /dev/null
    fi
}

# Entrypoint
case "${1:-}" in
    start) log_session_start ;;
    end)   log_session_end ;;
    init)  init_repo ;;
    *)     echo "Usage: work-logger.sh [start|end|init]" ;;
esac
